### ISSUE TITLE
SET vs. SEQUENCE

### ISSUE THREAD

**Issue by KeyvanArj** [gematik/ASN1Kit#6]
In ASN.1 there is difference between SET and SEQUENCE objects, I've changed the library to support both of them, If you would like I can send the pull request for it

**Comment by felix-handschuh** [comment]
Hey Keyvan, suggestions for improvements are always welcome. Just make a pull request and we will look at it as soon as possible and apply it if applicable.

Unfortunately, we haven't found a good way for us to do code annotations at the moment. Probably it will be an acknowledgement in the Read Me file on GitHub. But either way: thank you very much for your interest and help.

**Comment by sigabrtz** [comment]
Is this still relevant to you? Please create PRs for your suggestions.

In any case consider using Apple's https://github.com/apple/swift-asn1, since we might sunset this project at any moment.
